[project]
name = "flaskr"
version = "1.0.0"
description = "The basic blog app in the flask tutorial."
dependencies = ["flask"]

[build-system]
requires = ["flit-core<4"]
build-backend = "flit_core.buildapi"
